name: update

on:
  schedule:
    - cron: "30 5 * * *" 
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: auto-update
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install requirements
        run: npm install

      - name: Working
        run: node index.js

      - name: Commit files
        run: |
          git config --local user.email "dr_hamilton@foxmail.com"
          git config --local user.name "Ravello-H"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
